import GLib from 'gi://GLib';
import Lsp from 'gi://Lsp?version=3.0';

const assertEqual = (actual, expected, message) => {
    if (actual !== expected)
        throw new Error(`${message}: expected ${expected}, got ${actual}`);
};

const assert = (condition, message) => {
    if (!condition)
        throw new Error(message);
};

const makeRange = (startLine, startCharacter, endLine, endCharacter) => {
    const start = new Lsp.Position();
    start.init(startLine, startCharacter);
    const end = new Lsp.Position();
    end.init(endLine, endCharacter);
    const range = new Lsp.Range();
    range.init(start, end);
    return range;
};

const edit = new Lsp.TextEdit();
edit.init(makeRange(3, 4, 3, 9), 'print(${1:value})', null);

const item = Lsp.CompletionItem.new('print', Lsp.CompletionItemKind.FUNCTION);
item.set_label_details(Lsp.CompletionItemLabelDetails.new('(value)', 'GLib'));
item.set_documentation(Lsp.MarkupContent.new(
    Lsp.MarkupKind.MARKDOWN,
    '**Print** a value.',
));
item.set_commit_chars([';', '(']);
item.set_insert_text_format(Lsp.InsertTextFormat.SNIPPET);
item.set_text_edit(edit);
item.set_data(new GLib.Variant('s', 'completion-token'));

const completion = Lsp.CompletionList.from_variant(
    Lsp.CompletionList.new(true, [item]).to_variant(),
);
const [decodedItem] = completion.get_items();
assert(completion.get_is_incomplete(), 'completion list lost incomplete state');
assertEqual(decodedItem.get_label(), 'print', 'completion label did not round-trip');
assertEqual(decodedItem.get_insert_text_format(), Lsp.InsertTextFormat.SNIPPET,
    'insert text format did not round-trip');
assertEqual(decodedItem.get_text_edit().get_new_text(), 'print(${1:value})',
    'text edit did not round-trip');
assertEqual(decodedItem.get_data().deepUnpack(), 'completion-token',
    'completion data did not round-trip');

const rootUri = GLib.Uri.parse('file:///workspace', GLib.UriFlags.NONE);
const capabilities = Lsp.ServerCaps.new();
capabilities.set_text_document_sync(Lsp.TextDocumentSyncKind.INCREMENTAL);
capabilities.set_completion(Lsp.CompletionOptions.new(true, ['.', ':']));
capabilities.set_hover(true);

const params = Lsp.InitializeParams.new(null);
params.set_client_info(Lsp.ClientInfo.new('GJS Test Editor', '1.0'));
params.set_locale('en-US');
params.set_root_uri(rootUri);
params.set_trace(Lsp.TraceValue.MESSAGES);
params.set_workspaces([Lsp.WorkspaceFolder.new(rootUri, 'workspace')]);

const decodedParams = Lsp.InitializeParams.from_variant(params.to_variant());
assertEqual(decodedParams.get_client_info().get_name(), 'GJS Test Editor',
    'client info did not round-trip');
assertEqual(decodedParams.get_locale(), 'en-US', 'locale did not round-trip');
assertEqual(decodedParams.get_trace(), Lsp.TraceValue.MESSAGES,
    'trace did not round-trip');
assertEqual(decodedParams.get_workspaces().length, 1,
    'workspace folders did not round-trip');

const result = Lsp.InitializeResult.new(capabilities);
result.set_server_info(Lsp.ServerInfo.new('GJS Test Server', '1.0'));
const decodedResult = Lsp.InitializeResult.from_variant(result.to_variant());
assertEqual(decodedResult.get_capabilities().get_text_document_sync(),
    Lsp.TextDocumentSyncKind.INCREMENTAL,
    'text document sync capability did not round-trip');
assert(decodedResult.get_capabilities().get_completion().get_supports_resolve(),
    'completion resolve capability did not round-trip');
assert(decodedResult.get_capabilities().get_hover(),
    'hover capability did not round-trip');

const uri = GLib.Uri.parse(
    'file:///workspace/generated.vala',
    GLib.UriFlags.NONE,
);
const create = Lsp.CreateFile.new();
create.set_uri(uri);
create.set_options(Lsp.CreateFileOptions.OVERWRITE);
create.set_annotation_id('create-file');

const workspaceEdit = Lsp.WorkspaceEdit.new();
workspaceEdit.add_document_change(create);
workspaceEdit.set_change_annotation(
    'create-file',
    Lsp.ChangeAnnotation.new(
        'Create generated source',
        true,
        'The file is generated by the compiler.',
    ),
);

const decodedWorkspaceEdit = Lsp.WorkspaceEdit.from_variant(
    workspaceEdit.to_variant(),
);
const [documentChange] = decodedWorkspaceEdit.get_document_changes();
assert(documentChange instanceof Lsp.CreateFile,
    'workspace edit lost its typed document change');
assertEqual(documentChange.get_uri().to_string(), uri.to_string(),
    'workspace edit URI did not round-trip');
assertEqual(decodedWorkspaceEdit.get_change_annotations()['create-file'].get_label(),
    'Create generated source',
    'change annotation did not round-trip');
